---
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    filename: docker
  vars:
    deb_architecture: { "armv6l": "armhf", "armv7l": "armhf", "aarch64": "arm64", "x86_64": "amd64", "i386": "i386" }

- name: Install required packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
